name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create _headers file
        run: |
          echo "/*" > _headers
          echo "  Content-Type: text/html" >> _headers
          echo "*.js" >> _headers
          echo "  Content-Type: application/javascript" >> _headers
          echo "*.json" >> _headers
          echo "  Content-Type: application/json" >> _headers
          echo "service-worker.js" >> _headers
          echo "  Content-Type: application/javascript" >> _headers
          echo "  Service-Worker-Allowed: /" >> _headers

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          enable_jekyll: false
          force_orphan: true 